name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g. v1.2.3)"
        required: true
        type: string

jobs:
  build:
    name: build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-15-intel
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    env:
      CARGO_TERM_COLOR: always
      TAG_NAME: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: release-${{ matrix.target }}

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Package (unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          set -euo pipefail
          OUT="cgrep-${TAG_NAME}-${{ matrix.target }}"
          mkdir -p "dist/${OUT}"
          cp "target/${{ matrix.target }}/release/cgrep" "dist/${OUT}/"
          cp README.md CHANGELOG.md LICENSE-* "dist/${OUT}/" 2>/dev/null || true
          (cd dist && tar -czf "${OUT}.tar.gz" "${OUT}")
          if command -v shasum >/dev/null 2>&1; then
            shasum -a 256 "dist/${OUT}.tar.gz" > "dist/${OUT}.tar.gz.sha256"
          else
            sha256sum "dist/${OUT}.tar.gz" > "dist/${OUT}.tar.gz.sha256"
          fi
          rm -rf "dist/${OUT}"

      - name: Package (windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $out = "cgrep-$env:TAG_NAME-${{ matrix.target }}"
          New-Item -ItemType Directory -Force -Path "dist/$out" | Out-Null
          Copy-Item "target/${{ matrix.target }}/release/cgrep.exe" "dist/$out/"
          Copy-Item README.md, CHANGELOG.md, LICENSE-* "dist/$out/" -ErrorAction SilentlyContinue
          Compress-Archive -Path "dist/$out/*" -DestinationPath "dist/$out.zip" -Force
          $hash = (Get-FileHash "dist/$out.zip" -Algorithm SHA256).Hash.ToLower()
          "$hash  $out.zip" | Out-File -Encoding ASCII "dist/$out.zip.sha256"
          Remove-Item -Recurse -Force "dist/$out"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cgrep-${{ matrix.target }}
          path: dist/*
          if-no-files-found: error

  release:
    name: release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    env:
      TAG_NAME: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cgrep-*
          path: dist
          merge-multiple: true

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          generate_release_notes: true
          files: dist/*
